# This is a basic workflow to help you get started with Actions

name: Test & Upload to TestPyPI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8 

      - name: install
        run: |
          pip install -U pip setuptools
          pip install -U pytest twine
          pip install .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: |
          pytest
          
  upload: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build and Upload
        run: |
          python3 -m build
          python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TEST_TOKEN }}
          TWINE_REPOSITORY: testpypi
  
